pipeline:
  fanin:
    image: docker:20.10@sha256:41978d1974f05f80e1aef23ac03040491a7e28bd4551d4b469b43e558341864e
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker pull registry:5000/groot/backend:latest
    - docker pull registry:5000/groot/frontend:latest
    - test "$(docker inspect --format '{{ index .Config.Labels "based-on.base"}}' registry:5000/groot/backend:latest)" == "$(docker inspect --format '{{ index .Config.Labels "based-on.base"}}' registry:5000/groot/frontend:latest)"