version: "3.3"

services:

  proxy:
    image: traefik:3.0@sha256:916a4a86b36bb3576f39883573b0f932ed3f010bbbf35feab115bdbd5033566b
    command: "--debug --docker --docker.endpoint='unix:///var/run/docker.sock' --docker.watch=true --docker.exposedByDefault=false --entryPoints='Name:http Address::80' --defaultEntryPoints='http'"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    image: registry:2
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "HostRegexp: registry.{domain:.+}"
      traefik.port: 5000
      traefik.protocol: "http"

  web:
    image: konradkleine/docker-registry-frontend:v2
    depends_on:
      - registry
    environment:
      ENV_DOCKER_REGISTRY_HOST: "registry"
      ENV_DOCKER_REGISTRY_PORT: 5000
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "HostRegexp: hub.{domain:.+}"
      traefik.port: 80
      traefik.protocol: "http"
