pipeline:

  build:
    image: openjdk:19-jdk@sha256:c6f76c9bed82c777fbc57494dec14ca0dddf04a395da9f194055d2976549d2cb
    commands:
    - javac HelloWorld.java
    - jar -cvf HelloWorld.jar HelloWorld.class

  store:
    image: registry:5000/groot/tools
    commands:
    - curl -fT HelloWorld.jar -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]