pipeline:

  build:
    image: openjdk:20-jdk@sha256:48b71d82bf36b37dfd6e698a84be3abe1bee96debaa8a17d9fc6b3a7eadeed4f
    commands:
    - javac HelloWorld.java
    - jar -cvf HelloWorld.jar HelloWorld.class

  store:
    image: registry:5000/groot/tools
    commands:
    - curl -fT HelloWorld.jar -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]