pipeline:

  frontend:
    image: docker:18.09@sha256:58469a43b529313091f1df424037895a9961b27149aafec812ce8fd8d7ac0c9d
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag frontend frontend

  backend:
    image: docker:18.09@sha256:58469a43b529313091f1df424037895a9961b27149aafec812ce8fd8d7ac0c9d
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag backend backend