pipeline:

  frontend:
    image: docker:25.0@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag frontend frontend

  backend:
    image: docker:25.0@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag backend backend