pipeline:

  frontend:
    image: docker:18.06@sha256:d0ae46aa08806ffc1c4de70a4eb585df33470643a9d2ccf055ff3ec91ba5b0b0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag frontend frontend

  backend:
    image: docker:18.06@sha256:d0ae46aa08806ffc1c4de70a4eb585df33470643a9d2ccf055ff3ec91ba5b0b0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag backend backend