pipeline:

  frontend:
    image: docker:20.10@sha256:0e3e7e2033cf7779ab6985e24ad18d6ec415c9dd944acef5ca56119a3a0dda2e
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag frontend frontend

  backend:
    image: docker:20.10@sha256:0e3e7e2033cf7779ab6985e24ad18d6ec415c9dd944acef5ca56119a3a0dda2e
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag backend backend