pipeline:

  frontend:
    image: docker:23.0@sha256:3cf33ff6e893a39262bd9f6b85ff46e068fa2a98d201326e9c3058a22a21a6bb
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag frontend frontend

  backend:
    image: docker:23.0@sha256:3cf33ff6e893a39262bd9f6b85ff46e068fa2a98d201326e9c3058a22a21a6bb
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag backend backend