version: '{build}'
branches:
  only:
  - master
max_jobs: 1
image: Ubuntu
clone_depth: 1
clone_folder: /home/appveyor/projects/blog
environment:
  sftphost:
    secure: K+IBdbzrGeOB6TrWoKfjH7daOWKHdi1NC29EQpFWM6Q=
  sftpuser:
    secure: ohsHTmnC9yFEISEZZxbjCA==
  sftppass:
    secure: IYfz8DMZk78p0+8a17iCfol2qbi7HWFsHM+b8/iaTx8=
build_script:
- sh: >-
    git clone https://github.com/clarkwang/passh.git /home/appveyor/projects/passh

    cd /home/appveyor/projects/passh

    make

    cd /home/appveyor/projects/blog

    docker build --file Dockerfile.jekyll --tag jekyll .

    docker run --name jekyll jekyll jekyll build

    docker cp jekyll:/srv/jekyll/_site/ ./_site
deploy_script:
- sh: >-
    pwd

    cd _site

    echo -e "cd www\nput -r ." > sftp

    /home/appveyor/projects/passh/passh -p $sftppass bash -c "sftp -o BatchMode=no -o StrictHostKeyChecking=no -b sftp $sftpuser@$sftphost"
