pipeline:

  build:
    image: openjdk:8-jdk@sha256:86e863cc57215cfb181bd319736d0baf625fe8f150577f9eb58bd937f5452cb8
    commands:
    - javac HelloWorld.java
    - curl -fT HelloWorld.java -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/${CI_REPO_NAME}/${CI_BUILD_NUMBER}/
    - echo -n ${CI_BUILD_NUMBER} > latest
    - curl -fT latest -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/${CI_REPO_NAME}/

  trigger:
    image: plugins/downstream@sha256:03ff02d8a5637ea5197fa08929a91dfeeb5e30b1da62b82b6c2a895b170338ca
    server: https://ci.go-nerd.de
    fork: true
    repositories:
      - groot/hello-world-jar
    secrets: [ downstream_token ]