pipeline:
  build:
    image: docker:18.06@sha256:d0ae46aa08806ffc1c4de70a4eb585df33470643a9d2ccf055ff3ec91ba5b0b0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag registry:5000/groot/frontend .
    - docker push registry:5000/groot/frontend

  trigger:
    image: plugins/downstream@sha256:03ff02d8a5637ea5197fa08929a91dfeeb5e30b1da62b82b6c2a895b170338ca
    server: https://ci.go-nerd.de
    fork: true
    repositories:
      - groot/fan-in
    secrets: [ downstream_token ]