pipeline:
  build:
    image: docker:24.0@sha256:f44bd33ee57baf0830d8c07a1abd7ce40301a446e819b86ad0d99735c049f6a5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag registry:5000/groot/frontend .
    - docker push registry:5000/groot/frontend

  trigger:
    image: plugins/downstream
    server: https://ci.go-nerd.de
    fork: true
    repositories:
      - groot/fan-in
    secrets: [ downstream_token ]