pipeline:
  build:
    image: docker:18.06@sha256:d0ae46aa08806ffc1c4de70a4eb585df33470643a9d2ccf055ff3ec91ba5b0b0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag registry:5000/groot/base .
    - docker push registry:5000/groot/base

  trigger:
    image: plugins/downstream@sha256:b7924a1048636fbcf7ce9f0e706017c9b5ed705aa440ee8a76b387575f8b33e8
    server: https://ci.go-nerd.de
    fork: true
    repositories:
      - groot/backend
      - groot/frontend
    secrets: [ downstream_token ]