version: "3.3"

services:

  proxy:
    image: traefik:v2.8@sha256:4e52a5e2495484f5e19a49edfd2f652b0bce7b3603fa0df545ed90168ffae1c3
    command: "--debug --docker --docker.endpoint='unix:///var/run/docker.sock' --docker.watch=true --docker.exposedByDefault=false --entryPoints='Name:http Address::80' --defaultEntryPoints='http'"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    image: registry:2
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "HostRegexp: registry.{domain:.+}"
      traefik.port: 5000
      traefik.protocol: "http"

  web:
    image: konradkleine/docker-registry-frontend:v2
    depends_on:
      - registry
    environment:
      ENV_DOCKER_REGISTRY_HOST: "registry"
      ENV_DOCKER_REGISTRY_PORT: 5000
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "HostRegexp: hub.{domain:.+}"
      traefik.port: 80
      traefik.protocol: "http"
