pipeline:

  build:
    image: openjdk:20-jdk@sha256:e014e06874b05beb3024df48e740289b319e1796383a9d92525356718d78868f
    commands:
    - javac HelloWorld.java
    - ls -l
    - java HelloWorld

  docker:
    image: docker:18.06
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - ls -l
    - docker build --tag hello-world .
    - docker run hello-world