pipeline:

  build:
    image: openjdk:17.0.2-jdk@sha256:528707081fdb9562eb819128a9f85ae7fe000e2fbaeaf9f87662e7b3f38cb7d8
    commands:
    - javac HelloWorld.java
    - ls -l
    - java HelloWorld

  docker:
    image: docker:18.06
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - ls -l
    - docker build --tag hello-world .
    - docker run hello-world