pipeline:

  build:
    image: openjdk:8-jdk
    commands:
    - javac HelloWorld.java
    - ls -l
    - java HelloWorld

  docker:
    image: docker:20.10@sha256:75290344f118171da5c4525a3d08d726b8ec339808b21eec0ee792f35e55a30b
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - ls -l
    - docker build --tag hello-world .
    - docker run hello-world