pipeline:

  build:
    image: openjdk:19-jdk@sha256:c6f76c9bed82c777fbc57494dec14ca0dddf04a395da9f194055d2976549d2cb
    commands:
    - javac HelloWorld.java
    - ls -l
    - java HelloWorld

  docker:
    image: docker:18.06
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - ls -l
    - docker build --tag hello-world .
    - docker run hello-world