pipeline:

  build:
    image: openjdk:8-jdk
    commands:
    - javac HelloWorld.java
    - ls -l
    - java HelloWorld

  docker:
    image: docker:23.0@sha256:3cf33ff6e893a39262bd9f6b85ff46e068fa2a98d201326e9c3058a22a21a6bb
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - ls -l
    - docker build --tag hello-world .
    - docker run hello-world