pipeline:

  fetch:
    image: registry:5000/groot/tools
    commands:
    - LATEST=$(curl -f -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/groot/hello-world/latest)
    - curl -f -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" -o HelloWorld.jar https://webdav.dille.io/groot/hello-world/$${LATEST}/HelloWorld.java
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]

  build:
    image: docker:24.0@sha256:f44bd33ee57baf0830d8c07a1abd7ce40301a446e819b86ad0d99735c049f6a5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker build --tag registry:5000/${CI_REPO_NAME}:${CI_BUILD_NUMBER} --tag registry:5000/${CI_REPO_NAME}:dev .
    - docker push registry:5000/${CI_REPO_NAME}:${CI_BUILD_NUMBER}
    - docker push registry:5000/${CI_REPO_NAME}:dev

  test:
    image: docker:24.0@sha256:f44bd33ee57baf0830d8c07a1abd7ce40301a446e819b86ad0d99735c049f6a5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker run --rm registry:5000/${CI_REPO_NAME}:${CI_BUILD_NUMBER} test -f /tmp/testing

  publish:
    image: docker:24.0@sha256:f44bd33ee57baf0830d8c07a1abd7ce40301a446e819b86ad0d99735c049f6a5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - docker pull registry:5000/${CI_REPO_NAME}:${CI_BUILD_NUMBER}
    - docker tag registry:5000/${CI_REPO_NAME}:${CI_BUILD_NUMBER} registry:5000/${CI_REPO_NAME}:stable
    - docker push registry:5000/${CI_REPO_NAME}:stable