pipeline:

  build:
    image: openjdk:17.0.2-jdk@sha256:528707081fdb9562eb819128a9f85ae7fe000e2fbaeaf9f87662e7b3f38cb7d8
    commands:
    - javac HelloWorld.java
    - jar -cvf HelloWorld.jar HelloWorld.class

  store:
    image: registry:5000/groot/tools
    commands:
    - curl -fT HelloWorld.jar -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/${CI_REPO_NAME}/${CI_BUILD_NUMBER}/
    - echo -n ${CI_BUILD_NUMBER} > latest
    - curl -fT latest -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/${CI_REPO_NAME}/
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]