pipeline:

  fetch:
    image: registry:5000/groot/tools
    commands:
    - LATEST=$(curl -f -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/groot/artifact/latest)
    - curl -f -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" -o HelloWorld.jar https://webdav.dille.io/groot/artifact/$${LATEST}/HelloWorld.jar
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]

  docker:
    image: docker:24.0@sha256:f44bd33ee57baf0830d8c07a1abd7ce40301a446e819b86ad0d99735c049f6a5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - REGISTRY=registry:5000
    commands:
    - ls -l
    - docker build --tag registry:5000/groot/package .
    - docker push registry:5000/groot/package