pipeline:

  fetch:
    image: registry:5000/groot/tools
    commands:
    - LATEST=$(curl -f -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" https://webdav.dille.io/groot/artifact/latest)
    - curl -f -u "$${WEBDAV_USER}:$${WEBDAV_PASS}" -o HelloWorld.jar https://webdav.dille.io/groot/artifact/$${LATEST}/HelloWorld.jar
    secrets: [ WEBDAV_USER, WEBDAV_PASS ]

  docker:
    image: docker:20.10@sha256:0e3e7e2033cf7779ab6985e24ad18d6ec415c9dd944acef5ca56119a3a0dda2e
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - REGISTRY=registry:5000
    commands:
    - ls -l
    - docker build --tag registry:5000/groot/package .
    - docker push registry:5000/groot/package